blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://forum.deeppavlov.ai/
    about: If you have a different question, please ask it in the forum https://forum.deeppavlov.ai
